### PR TITLE
Updated to @solana/web3.js lib version 2

### PR DESCRIPTION
**Pull request by wjthieme**
hi @kevinheavey, love solana-bankrun! we're in the process of updating our sdk to the new version of `@solana/web3.js` (currently in release-candidate). Would be great if we can use bankrun with our new sdk. I just updated functions to use the new web3.js types. Let me know what you think! 

Had to update CI to use node v20 because of the availability of `cypto`. Older versions of node can still work but require a polyfill for `crypto`.

Potentially this can be left as a PR/branch (until `@solana/web3.js` v2 is fully released) and be released as a beta version `0.4.0-beta.0` or something.

### CODE REVIEW

**Comment by wjthieme** [comment]
Hi @kevinheavey. Would you be able to release this as an alpha/beta version on npm? I would rather not have to resort back to `solana-test-validator` for our e2e tests 🙏🏼

**Comment by kevinheavey** [comment]
> Would you be able to release this as an alpha/beta version on npm?

Sorry, the users are too dumb to expose them to something like this. I recommend publishing a one-off release yourself. I will move solana-bankrun to web3.js 2.0 when it is recommended. This work is helpful though, thank you

**Comment by wjthieme** [comment]
> Sorry, the users are too dumb to expose them to something like this.

If you release this as `solana-bankrun@0.5.0-beta.1` or something using the npm tag `beta` it would only be installable if you explicitly set version to 0.5.0-beta.1. For all other purposes version 0.4.0 will still show up as the latest version. Anyone doing `npm install solana-bankrun` will still get version 0.4.0.

**Comment by kevinheavey** [comment]
For the sake of not leaving you waiting for a response I will confirm that I don't plan on releasing a beta version

**Pull request closed without merging**
